# reusable workflow
name: .build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      vars:
        required: false
        type: string
      release:
        required: false
        type: string
      distros:
        required: false
        type: string
      dockerhub_username:
        required: false
        type: string
    secrets:
      rh_user:
        required: false
      rh_pass:
        required: false
      dockerhub_token:
        required: false

env:
  REPO_SLUG: dockereng/packaging
  BUILD_CACHE_REGISTRY_SLUG: dockereng/packaging-cache
  DOCKER_BUILD_SUMMARY: false

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      includes: ${{ steps.matrix.outputs.includes }}
      verifications: ${{ steps.matrix.outputs.verifications }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      -
        name: Matrix
        id: matrix
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          INPUT_NAME: ${{ inputs.name }}
          INPUT_RELEASE: ${{ inputs.release }}
          INPUT_DISTROS: ${{ inputs.distros }}
          INPUT_VARS: ${{ inputs.vars }}
        with:
          script: |
            const inpName = core.getInput('name');
            const inpRelease = core.getInput('release');
            const inpDistros = core.getInput('distros');
            const inpVars = core.getMultilineInput('vars');

            let distroFilter = [];
            if (inpDistros) {
              distroFilter = inpDistros.split(',').map(d => d.trim()).filter(d => d !== '');
            }
            
            if (inpRelease !== '' && !['pushonly', 'draft', 'prerelease', 'release'].includes(inpRelease)) {
              throw new Error(`Invalid release type: ${inpRelease}`);
            }
            
            let def = {};
            await core.group(`Parsing definition`, async () => {
              const bakeArgs = ['buildx', 'bake'];
              for (const v of inpVars) {
                bakeArgs.push('--var', v);
              }
              bakeArgs.push('pkg', '--print');
              const resPrint = await exec.getExecOutput('docker', bakeArgs, {
                ignoreReturnCode: true
              });
              if (resPrint.stderr.length > 0 && resPrint.exitCode != 0) {
                throw new Error(resPrint.stderr);
              }
              def = JSON.parse(resPrint.stdout.trim());
            });
            
            await core.group(`Generating matrix`, async () => {
              const includes = [];
              const verifications = [];
              for (const targetName of Object.keys(def.target)) {
                if (!targetName.startsWith(`pkg-${inpName}-`)) {
                  continue;
                }
                const match = targetName.match(/^pkg-(.+)-([^-]+)$/);
                if (!match) {
                  throw new Error(`Invalid target name: ${targetName}`);
                }
                const distro = match[2];
                if (distroFilter.length > 0 && !distroFilter.includes(distro)) {
                  core.info(`Skipping ${targetName} because it doesn't match the input distro filter`);
                  continue;
                }
                const target = def.target[targetName];
                if (target.platforms && target.platforms.length > 0) {
                  includes.push({
                    distro: distro
                  });
                  target.platforms.forEach(platform => {
                    // FIXME: we can't verify platforms not native to the runner as it would segfault through emulation
                    if (platform.startsWith('linux/386') || platform.startsWith('linux/amd64') || platform.startsWith('linux/arm64')) {
                      verifications.push({
                        distro: distro,
                        platform: platform,
                        runner: platform.startsWith('linux/arm') ? 'ubuntu-24.04-arm' : 'ubuntu-24.04'
                      });
                    }
                  });
                } else {
                  // if no platforms are returned, this means this package does
                  // not support a distro so we skip it.
                }
              }
              if (includes.length === 0) {
                throw new Error(`No package targets found for ${inpName}`);
              }
              core.info(JSON.stringify(includes, null, 2));
              core.info(JSON.stringify(verifications, null, 2));
              core.setOutput('includes', JSON.stringify(includes));
              core.setOutput('verifications', JSON.stringify(verifications));
            });

  # TODO: add RH_USER and RH_PASS to the build job once we have a way to pass secrets: https://github.com/docker/github-builder/pull/248
  build:
    uses: docker/github-builder/.github/workflows/bake.yml@3415a188caae9a0da7fba83bc06985776e0b1790 # v1.14.0
    permissions:
      contents: read
      id-token: write
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.includes) }}
    with:
      job-name-prefix: ${{ matrix.distro }}
      artifact-name: build-pkg-${{ inputs.name }}-${{ matrix.distro }}
      artifact-upload: true
      artifact-retention-days: 1
      output: local
      sbom: true
      sign: ${{ github.event_name != 'pull_request' }}
      target: pkg-${{ inputs.name }}-${{ matrix.distro }}
      vars: |
        ${{ inputs.vars }}

  verify:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    if: ${{ needs.prepare.outputs.verifications != '[]' }}
    needs:
      - prepare
      - build
    env:
      INPUT_NAME: ${{ inputs.name }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.verifications) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      -
        name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-pkg-${{ inputs.name }}-${{ matrix.distro }}
          path: ./bin/pkg/${{ inputs.name }}/${{ matrix.distro }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
        with:
          version: latest
      -
        name: List artifacts
        run: |
          tree -nh "./bin/pkg/${INPUT_NAME}"
      -
        name: Verify
        uses: docker/bake-action@d3418bd7d0e9324001bca92fa8ba175ea7e6dc9b # v7.3.0
        with:
          source: .
          targets: verify-${{ inputs.name }}-${{ matrix.distro }}
          vars: |
            ${{ inputs.vars }}
          set: |
            *.platform=${{ matrix.platform }}

  release:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    if: ${{ always() && needs.build.result == 'success' && (needs.verify.result == 'success' || needs.verify.result == 'skipped') }}
    needs:
      - prepare
      - build
      - verify
    env:
      INPUT_INCLUDES: ${{ needs.prepare.outputs.includes }}
      INPUT_NAME: ${{ inputs.name }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
        with:
          version: latest
      -
        name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: /tmp/build-pkg
          pattern: build-pkg-${{ inputs.name }}-*
          merge-multiple: false
      -
        name: Arrange artifacts
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          INPUT_INCLUDES: ${{ needs.prepare.outputs.includes }}
          INPUT_NAME: ${{ inputs.name }}
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const inputName = core.getInput('name');
            const includes = JSON.parse(core.getInput('includes'));
            const destinationRoot = path.join('bin', 'pkg', inputName);

            fs.mkdirSync(destinationRoot, {recursive: true});
            for (const include of includes) {
              const artifact = path.join('/tmp', 'build-pkg', `build-pkg-${inputName}-${include.distro}`);
              if (!fs.existsSync(artifact) || !fs.statSync(artifact).isDirectory()) {
                core.setFailed(`missing artifact: ${artifact}`);
                return;
              }
              const destination = path.join(destinationRoot, include.distro);
              fs.mkdirSync(destination, {recursive: true});
              fs.cpSync(artifact, destination, {recursive: true, force: true});
            }
      -
        name: List artifacts
        run: |
          tree -nh "./bin/pkg/${INPUT_NAME}"
      -
        name: Generate metadata
        uses: docker/bake-action@d3418bd7d0e9324001bca92fa8ba175ea7e6dc9b # v7.3.0
        with:
          source: .
          targets: metadata-${{ inputs.name }}
          vars: |
            ${{ inputs.vars }}
          provenance: false
      -
        name: Resolve metadata
        run: |
          while IFS= read -r l; do
            export "${l?}"
            printf '%s\n' "${l?}" >> "$GITHUB_ENV"
          done < "./bin/pkg/${INPUT_NAME}/metadata.env"
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "GIT_TAG=nightly/${INPUT_NAME}/$VERSION" >> "$GITHUB_ENV"
          else
            echo "GIT_TAG=${INPUT_NAME}/$VERSION" >> "$GITHUB_ENV"
          fi
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: |
            ${{ env.REPO_SLUG }}
          tags: |
            type=ref,event=pr
            type=raw,value=${{ env.GIT_TAG }}
            type=raw,value=${{ env.GIT_TAG }}-${{ github.run_number }}
          labels: |
            com.github.docker.packaging.event_name=${{ github.event_name }}
            com.github.docker.packaging.run_id=${{ github.run_id }}
            com.github.docker.packaging.run_number=${{ github.run_number }}
          bake-target: meta-helper
      -
        name: Login to Docker Hub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        if: ${{ inputs.release || github.event_name == 'schedule' }}
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
      -
        name: Build release
        id: build
        uses: docker/bake-action@d3418bd7d0e9324001bca92fa8ba175ea7e6dc9b # v7.3.0
        with:
          source: .
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file-tags }}
            ${{ steps.meta.outputs.bake-file-annotations }}
          targets: release-${{ inputs.name }}
          vars: |
            ${{ inputs.vars }}
          provenance: false
          set: |
            *.output=type=image,oci-mediatypes=true,push=${{ inputs.release != '' || github.event_name == 'schedule' }}
            *.output=/tmp/release
      -
        name: List release artifacts
        run: |
          mkdir -p /tmp/release-squashed
          cp "./bin/pkg/${INPUT_NAME}/metadata.env" /tmp/release-squashed/
          find /tmp/release -mindepth 2 -maxdepth 2 ! -name metadata.env -exec cp -r -t /tmp/release-squashed {} +
          tree -nh /tmp/release-squashed | tee /tmp/packages.txt
          rm -rf /tmp/release-squashed
      -
        name: Prepare release
        run: |
          cat > "/tmp/release-metadata.json" <<-EOF
          ${{ steps.build.outputs.metadata }}
          EOF
          
          for tag in $(jq -r '.tags[]' <<< "$DOCKER_METADATA_OUTPUT_JSON"); do
            echo "* \`${tag}\`" >> /tmp/tags.txt
          done
          
          cat > "/tmp/summary.txt" <<-EOF
          * repo: ${REPO}
          * ref: \`${REF}\`
          * version: \`${VERSION}\`
          * commit: [\`${COMMIT}\`](${REPO}/commit/${COMMIT})
          EOF

          if [ "$INPUT_NAME" = "containerd" ]; then
            cat >> "/tmp/summary.txt" <<-EOF
          * runc
            * repo: ${RUNC_REPO}
            * ref: \`${RUNC_REF}\`
            * version: \`${RUNC_VERSION}\`
            * commit: [\`${RUNC_COMMIT}\`](${RUNC_REPO}/commit/${RUNC_COMMIT})
          * runhcs
            * repo: ${RUNHCS_REPO}
            * ref: \`${RUNHCS_REF}\`
            * version: \`${RUNHCS_VERSION}\`
            * commit: [\`${RUNHCS_COMMIT}\`](${RUNHCS_REPO}/commit/${RUNHCS_COMMIT})
          EOF
          fi
          
          cat >> "/tmp/summary.txt" <<-EOF
          * packages: \`$(find /tmp/release -type f | wc -l)\` files
          * size: \`$(du -sh /tmp/release | awk '{print $1}')\`
          EOF
          
          cat >> "$GITHUB_STEP_SUMMARY" <<-EOF
          # Package build
          
          ## Tags
          $(cat /tmp/tags.txt)
          
          ## Summary
          $(cat /tmp/summary.txt)
          EOF
      -
        name: Set outputs
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        id: release-metadata
        with:
          script: |
            const fs = require('fs');
            core.setOutput('tags', fs.readFileSync('/tmp/tags.txt', {encoding: 'utf8'}));
            core.setOutput('summary', fs.readFileSync('/tmp/summary.txt', {encoding: 'utf8'}));
      -
        name: Create release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228  # v3.0.2
        if: ${{ inputs.release && inputs.release != 'pushonly' }}
        with:
          name: ${{ env.GIT_TAG }}-${{ github.run_number }}
          draft: ${{ inputs.release == 'draft' }}
          prerelease: ${{ inputs.release == 'prerelease' }}
          tag_name: ${{ env.GIT_TAG }}-${{ github.run_number }}
          target_commitish: ${{ github.sha }}
          files: |
            /tmp/packages.txt
            ./bin/pkg/${{ inputs.name }}/metadata.env
            /tmp/release-metadata.json
          body: |
            Image available at [https://hub.docker.com/r/${{ env.REPO_SLUG }}](https://hub.docker.com/r/${{ env.REPO_SLUG }}).

            ## Tags
            ${{ steps.release-metadata.outputs.tags }}

            ## Summary
            ${{ steps.release-metadata.outputs.summary }}

            ## Usage
            Extract with [Undock](https://github.com/crazy-max/undock):
            ```console
            $ undock --wrap --rm-dist --all ${{ env.REPO_SLUG }}:${{ steps.meta.outputs.version }} ./${{ inputs.name }}/${{ env.VERSION }}
            ```
        env:
          GITHUB_TOKEN: ${{ github.token }}
