# This workflow runs nighly builds for each package.
name: nightly

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0'

jobs:
  pkgs:
    uses: ./.github/workflows/.pkgs.yml

  build:
    uses: ./.github/workflows/.build.yml
    permissions:
      contents: read
    needs:
      - pkgs
    strategy:
      fail-fast: false
      matrix:
        pkg: ${{ fromJson(needs.pkgs.outputs.list) }}
    with:
      name: ${{ matrix.pkg }}
      release: pushonly
      envs: |
        NIGHTLY_BUILD=1
      dockerhub_username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
    secrets:
      rh_user: ${{ secrets.RH_USER }}
      rh_pass: ${{ secrets.RH_PASS }}
      dockerhub_token: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}
